thruster-rs/Thruster

README.md

Here are a few minor changes to phrasing to make the README flow better.

Tweak phrasing in README

---

Cargo.toml
LICENSE.md
README.md
examples/hello_world/context.rs
examples/hello_world/main.rs
examples/most_basic.rs
src/app.rs
src/context.rs
src/lib.rs
src/middleware.rs
src/request.rs
src/route_parser.rs

Add documentation, license, and bump version

---

Cargo.toml
README.md
examples/hello_world/context.rs
examples/hello_world/main.rs
examples/most_basic.rs
src/app.rs
src/lib.rs
src/middleware.rs
src/request.rs
src/response.rs
src/route_parser.rs
src/route_tree/mod.rs
src/route_tree/node.rs

Swap out Vec for SmallVec to improve heap performance. Also update the documentation link in the README.md

feat: Improve performance using SmallVec

---

README.md
examples/most_basic.rs
src/app.rs
src/lib.rs
src/route_parser.rs

bug: fix examples and README file

---

Cargo.toml
README.md
benches/app.rs
examples/hello_world/main.rs
examples/most_basic.rs
src/app.rs
src/lib.rs

This PR:
- Uses Criterion for benchmarking
- Moves from Vec to SmallVec

feat: move to stable and swap out for smallvec

---

src/app.rs
src/route_tree/mod.rs
src/route_tree/node.rs

**Issue:** A few things are going awry currently:
- `/a/:id` gets matched for `/a/1/b/c`
- `/*` doesn't get matched for missing routes
**Solution:** Add a terminal node passing through the route matching and also check if paramaterized nodes actually are matched with a piece of the route.

bug: Fix wildcarding routes

---

README.md
examples/run_test/main.rs
src/app.rs
src/lib.rs
src/testing/mod.rs

Adds a testing harness to making testing routes much easier.

feat: Add testing harness

---

src/app.rs

bug: Disable certain functions for windows

---

README.md

chore: Update readme to include generator

---

examples/multicontext.rs

Add a simple example that uses multiple contexts, a basic example for #84
In the future, once we can store some semblance of impl traits, we'll be able to remove this in favor of a more thorough solution.

feat: Add multi context example

---

Cargo.toml
src/app.rs
src/request.rs

**Issue:** Header values as well as keys are being lowercased.
**Solution:** Do not lowercase header values.

bug: Do not lowercase header values

---

README.md

Make the readme look better by adding badges and a bit of rearranging with the old content.
cc @trezm

Update crate meta

---

thruster-app/Cargo.toml
thruster-async-await/Cargo.toml
thruster-context/Cargo.toml
thruster-context/src/basic_context.rs
thruster-context/src/basic_hyper_context.rs
thruster-core-async-await/Cargo.toml
thruster-core/Cargo.toml
thruster-core/src/response.rs
thruster-middleware/Cargo.toml
thruster-proc/Cargo.toml
thruster-server/Cargo.toml
thruster/Cargo.toml
thruster/examples/hello_world/context.rs

Allows the server header to be changed. Should resolve [#106]

feat: Allow "Server" header to be changed [106]

---

thruster-app/Cargo.toml
thruster-async-await/Cargo.toml
thruster-async-await/src/lib.rs
thruster-context/Cargo.toml
thruster-core-async-await/Cargo.toml
thruster-core/Cargo.toml
thruster-middleware/Cargo.toml
thruster-proc/Cargo.toml
thruster-server/Cargo.toml
thruster/Cargo.toml
thruster/examples/async_await.rs
thruster/examples/most_basic_async.rs

Refactor the most basic examples to be more basic. Also fix an issue with using async_await without the error handler.

chore: Refactor and update examples

---

publish_helper.sh
thruster-app/Cargo.toml
thruster-async-await/Cargo.toml
thruster-context/Cargo.toml
thruster-context/src/basic_hyper_context.rs
thruster-core-async-await/Cargo.toml
thruster-core/Cargo.toml
thruster-middleware/Cargo.toml
thruster-proc/Cargo.toml
thruster-server/Cargo.toml
thruster-server/src/ssl_hyper_server.rs
thruster/Cargo.toml

bug: Fix ssl hyper server to return future

---

README.md
publish_helper.sh
thruster-proc/Cargo.toml
thruster/Cargo.toml
thruster/benches/app.rs
thruster/examples/error_handling.rs
thruster/examples/hello_world.rs
thruster/examples/hyper_most_basic.rs
thruster/examples/hyper_most_basic_ssl/main.rs
thruster/examples/most_basic_ssl/main.rs
thruster/examples/multiple_services.rs
thruster/examples/profiling.rs
thruster/examples/static_file/main.rs
thruster/src/context/basic_hyper_context.rs
thruster/src/core/middleware.rs
thruster/src/integration_async_tests.rs
thruster/src/lib.rs
thruster/src/middleware/cors.rs
thruster/src/middleware/file.rs
thruster/src/middleware/mod.rs

- Adds a more helpful end of chain (EOC) message for the developer.
- Ran `cargo fmt` across the board
- Added CORS middleware

chore: Add more helpful EOC message

---

thruster/src/core/context.rs

Adds documentation for the Context trait.

chore: Add documentation for the Context trait

---

README.md
thruster/src/app/testing.rs
thruster/src/app/testing_async.rs
thruster/src/app/thruster_app.rs
thruster/src/core/date.rs
thruster/src/core/route_tree/mod.rs

Also update some `&'static str` references to `&str`.
`cargo test` seems to run well

Changed UPDATE to PATCH

---

README.md
RELEASE.md
thruster-proc/Cargo.toml
thruster/Cargo.toml
thruster/src/server/hyper_server.rs

Celebrating our 1.0.0 release!

chore: Update readme and such

---

thruster/examples/jwt_example/jwt_context.rs
thruster/src/context/basic_context.rs
thruster/src/context/basic_hyper_context.rs
thruster/src/context/typed_hyper_context.rs
thruster/src/core/request.rs
thruster/src/core/route_tree/node.rs
thruster/src/middleware/cookies.rs
thruster/src/middleware/query_params.rs

Also fixes a quick bug that appeared in the route parameters that was preventing them from being fulfilled.

bug: Fix cookie middleware

---

thruster-proc/Cargo.toml
thruster/Cargo.toml
thruster/src/context/hyper_request.rs
thruster/src/server/hyper_server.rs

Note that this might cause a slowdown. Although I haven't tested it yet, we are copying an extra piece of data for hyper requests.

feat: Add ip to hyper requests

---

thruster/src/context/basic_context.rs

Added json and set_status methods in BasicContext. This is similar to one in express as 
```js
res.json(...)
```
I'm the one who reported issue on reddit 😀 https://www.reddit.com/r/rust/comments/nsiqlk/thruster_112_release_an_expresslike_http_server/h0nzs60?utm_source=share&utm_medium=web2x&context=3

added json and set_status methods for basic context

---

thruster-proc/Cargo.toml
thruster-proc/src/lib.rs
thruster/Cargo.toml
thruster/benches/app.rs
thruster/cargo/BUILD.bazel
thruster/examples/grpc/build.rs
thruster/examples/grpc/cargo/BUILD.bazel
thruster/examples/nesting.rs
thruster/examples/profiling.rs
thruster/examples/unix_socket.rs
thruster/examples/using_state.rs
thruster/src/app/mod.rs
thruster/src/app/testing_async.rs
thruster/src/app/testing_hyper_async.rs
thruster/src/app/thruster_app.rs
thruster/src/context/basic_context.rs
thruster/src/context/basic_hyper_context.rs
thruster/src/context/typed_hyper_context.rs
thruster/src/core/request.rs
thruster/src/lib.rs
thruster/src/parser/tree.rs
thruster/src/server/homegrown_server.rs
thruster/src/server/hyper_server.rs
thruster/src/server/ssl_hyper_server.rs
thruster/src/server/ssl_server.rs
thruster/src/server/unix_hyper_server.rs

Also fixes quite a few lints that got out of hand!

bug: Fix nested apps and bump version

---

thruster-proc/Cargo.toml
thruster/Cargo.toml
thruster/examples/actix_most_basic.rs
thruster/src/app/testing_async.rs
thruster/src/app/testing_hyper_async.rs
thruster/src/app/thruster_app.rs
thruster/src/context/actix_request.rs
thruster/src/context/basic_actix_context.rs
thruster/src/context/mod.rs
thruster/src/context/typed_hyper_context.rs
thruster/src/server/actix_server.rs
thruster/src/server/mod.rs
thruster/src/server/thruster_server.rs

I was tired of hyper getting all the love -- so I added an actix backend too.

fea: Add actix-web backend

---

thruster/Cargo.toml
thruster/src/app/thruster_app.rs

Adds aliases for methods that make a little more sense and adhere to standards across other http frameworks

feat: Add aliases for methods

---

thruster-proc/Cargo.toml
thruster/Cargo.toml
thruster/src/lib.rs

This is so we can explore integration with shuttle.rs, which seems pretty great.

chore: Expose ThrusterRequest

---

thruster/src/app/mod.rs
thruster/src/app/testing_hyper_async.rs

Instead of a String. Much easier this way for testing harnesses.

chore: Make Testable trait use str

---

thruster/src/app/mod.rs
thruster/src/app/testing_hyper_async.rs

Had a typo -- also added proper method to the request builder.

bug: Make option options in testing module

---

README.md

fix(readme): English typo

---

thruster-proc/Cargo.toml
thruster-proc/src/lib.rs
thruster/Cargo.toml
thruster/examples/custom_middleware_with_auth.rs
thruster/examples/using_state.rs
thruster/src/parser/tree.rs

This should be in preparation for easier third party modules. The goal is to be able to simply add a module without having to implement traits, while also not sacrificing performance or simplicity.

feat: Add easier state handling

---

thruster-proc/Cargo.toml
thruster/Cargo.toml
thruster/src/app/thruster_app.rs

Reverts thruster-rs/Thruster#256

Revert "feat: Add message in errors as context body"
