thruster-rs/Thruster

Cargo.toml, README.md, examples/hello_world/context.rs, examples/most_basic.rs, src/app.rs
The context generators don't actually need access to the handle since the handle is available more cleanly via the MiddlewareChain struct. This will simplify the generator signature and limit the number of ways to access the current tokio handle.
=> bug: Remove extraneous handle in ctx generation

Cargo.toml, README.md, src/app.rs, src/route_parser.rs
**Issue:** When using a subapp, the parameter is not correctly recognized.
**Solution:** This was happening because we were checking for the new route with the old route parser hashmap, i.e. we were checking for `/*` instead of `/test/*`. We shouldn't need to traverse through the map again at all given that we already know what the node should be, so now we bypass the lookup and directly pass the route node in.
=> bug: Fix bug in params in subapps

examples/hello_world/main.rs
There doesn't seem to be any reason that you need `#[feature(test)]` in this example, and it seems having it prevents `cargo test` to run with stable rust.
=> Remove feature(test) from hello_world example

README.md, src/app.rs, src/route_tree/mod.rs, src/route_tree/node.rs
**Issue:** Middleware was not properly getting copied over for the base of a tree into the new subtree at the correct route.
**Solution:** Ensure that when a new subtree is added, the middleware on the root node is _also_ added.
=> bug: Fix base routes of subtrees

Cargo.toml, src/app.rs, src/request.rs
**Issue:** Requests will not work with pipelines.
**Solution:** Right now requests assume each connection is a single full request. This PR changes that so that `Content-Length` is respected, or the body is assumed to be `0` bytes in the case where `Content-Length` is absent. Note that this doesn _not_ cover chunked data yet.
=> bug: Allow pipelined requests

Cargo.toml, src/app.rs, src/http.rs, src/lib.rs, src/request.rs, src/response.rs, src/route_parser.rs
- Brought back in `templatify` which is more performant than `format!`.
- Removed header iterator which was happening twice
- Moved query string to checking out of shortcuts -- might need to revert this in the future or think of a better option.
=>  feat: Improve performance again

CONTRIBUTING.md, Cargo.toml, README.md, benches/app.rs, examples/hello_world/context.rs, examples/hello_world/main.rs, examples/most_basic.rs, src/app.rs, src/builtins/basic_context.rs, src/builtins/mod.rs, src/builtins/query_params.rs, src/builtins/retains_request.rs, src/context.rs, src/lib.rs, src/middleware.rs, src/request.rs, src/response.rs, src/route_parser.rs, src/route_tree/mod.rs, src/route_tree/node.rs
This PR:
- Allows the option to optimize for small requests via `start_small_load_optimized`
- Moves query params into a middleware so not all routes are slowed by processing query parameters by default
- Removes safety check from middleware. If, for example, a terminal piece of middleware calls next, you'll see an exception. This might be added back in in the future.
- Adds a CONTRIBUTING.md file (#51)
=> feat: Improve perf, migrate query params to middleware

examples/hello_world/context.rs, examples/hello_world/main.rs, src/app.rs, src/request.rs, src/route_tree/mod.rs, src/route_tree/node.rs
**Issue:** Nested routes if they miss do not default to a parent wildcard (`*`) route.
**Solution:** I re-added the concept of a "terminal node" into the tree. If a route does not match a terminal node, it will trace back up its stack until it finds a terminal node and use its middleware. If no terminal node is found, then no middleware is passed and an assertion will fail.
Resolves [#53]
=> bug: Fix nested routes with wildcards

src/app.rs, src/route_tree/mod.rs, src/route_tree/node.rs
**Issue:** Thruster wasn't doing well with wildcard routes in subapps.
**Solution:** This was happening because we were mislabeling terminal nodes as well as not assigning wildcard nodes appropriately.
=> bug: Fix how we do subapps and wildcards

src/app.rs, src/route_tree/node.rs
**Issue:** Paramaterized nodes, e.g. `:id`, are always being made to be terminal.
**Solution:** Do not do so, as the recursion takes care of that if the next piece is 0 length.
=> bug: fix paramaterized nodes treated terminally

Cargo.toml, examples/diesel/.env, examples/diesel/content_model.rs, examples/diesel/context.rs, examples/diesel/main.rs, examples/diesel/migrations/00000000000000_diesel_initial_setup/down.sql, examples/diesel/migrations/00000000000000_diesel_initial_setup/up.sql, examples/diesel/migrations/2018-09-07-121333_create_content/down.sql, examples/diesel/migrations/2018-09-07-121333_create_content/up.sql, examples/diesel/migrations/2018-09-07-130042_add_content/down.sql, examples/diesel/migrations/2018-09-07-130042_add_content/up.sql, examples/diesel/schema.rs, examples/hello_world/main.rs
Add a diesel example using `lazy_static` and `r2d2` as a connection pool. This is similar to how the standard practice in Node is with singleton modules.
=> feat: Add diesel example

README.md, examples/run_test/main.rs, src/app.rs, src/testing/mod.rs
Replaces the output with a `TestResponse` struct instead of a single string. The test struct has `body` for the body, `headers` for the headers, and `status` as a pair of code and message.
Resolves #65
=> feat: Add headers and status to test harness

src/app.rs, src/request.rs
**Issue:** When in chrome, loading the page once in the `most_basic` example loads successfully. Subsequent refreshes yield `ERR_EMPTY_RESPONSE`.
**Solution:** This was happening because we had too small a vector for headers. Chrome, for one reason or another, treats the first and refresh requests differently as far as headers go. This is also why we were not seeing the issue in tests or in using `curl`. The header size array has been increased to 32 now.
Resolves #67
=> bug: Refreshing in Chrome causes `ERR_EMPTY_RESPONSE`

examples/cookies/main.rs, src/app.rs, src/builtins/basic_context.rs, src/lib.rs, src/request.rs
This gives `BasicContext` more functionality. Specifically:
- `set` Sets a header
- `remove` Removes a header
- `status` Sets the status
- `content_type` Sets the `Content-Type` header (a convenience method for `set("Content-Type", "whatever")`
- `redirect` Sets the status code to 302 if not 301 (can be changed after,) and the `Location` header.
- `cookie` Sets a cookie
Resolves #70
=> feat: Give BasicContext more functionality

src/app.rs, src/route_tree/mod.rs, src/route_tree/node.rs
**Issue:** If `/` is defined as well as `/*`, the wildcard takes precedence, where the opposite should be true.
**Solution:** The matching algorithm was off. We should reexamine and refactor the matching algorithm in the future.
[Fixes #73]
=> bug: Fix index route conflict with *

Cargo.toml, README.md, benches/app.rs, examples/diesel/context.rs, examples/diesel/main.rs, examples/hello_world/context.rs, examples/hello_world/main.rs, examples/hyper_most_basic.rs, examples/most_basic.rs, examples/run_test/main.rs, src/app.rs, src/builtins/basic_hyper_context.rs, src/builtins/hyper_server.rs, src/builtins/mod.rs, src/builtins/query_params.rs, src/builtins/retains_request.rs, src/builtins/server.rs, src/context.rs, src/lib.rs, src/request.rs, src/route_parser.rs, src/server.rs, src/testing/mod.rs
This allows the router to be functionally separated from the backend. Included is an example to use Hyper as the server backend with Thruster as a router over it.
=> feat: Allow for generic backends

Cargo.toml, README.md, benches/app.rs, examples/cookies/main.rs, examples/diesel/main.rs, examples/hello_world/main.rs, examples/hyper_most_basic.rs, examples/most_basic.rs, examples/multicontext.rs, examples/run_test/main.rs, src/app.rs, src/builtins/query_params.rs, src/lib.rs, src/middleware.rs, src/request.rs, src/route_parser.rs, src/route_tree/mod.rs, src/route_tree/node.rs
Moves to a macro that chains together functions rather than relying on a struct. This enables us to use mutliple different contexts in a single app as long as the contexts implement into and from each other.
[Fixes [84]](https://github.com/trezm/Thruster/issues/84)
=> feat: Move to chainable instead of a middleware object

Cargo.toml, examples/cookies/main.rs, examples/most_basic.rs, examples/multicontext.rs, examples/run_test/main.rs, src/app.rs, src/builtins/basic_context.rs, src/route_tree/mod.rs
Right now we automatically cast to utf8 into a BasicContext. This isn't tenable for non-string based files -- so now `BasicContext.set_body` will _not_ attempt to cast to utf8 prior to passing the data to the response.
=> feat: Do not cast body to utf8 string in BasicContext

examples/hyper_most_basic.rs, src/builtins/basic_hyper_context.rs
Now that `set_body` accepts a `Vec<u8>`, there's no need for this UTF8 check/conversion in the Hyper context. It can go directly into a Hyper `Body`, which should be a little more efficient.
=> Avoid unnnecessary String conversions in Hyper context

README.md
Should be `Ctx => plaintext`, not just `plaintext`.
Resolves [[#96]](https://github.com/trezm/Thruster/issues/96)
=> bug(readme): Fix error in readme

README.md, thruster-async-await/Cargo.toml, thruster-async-await/src/lib.rs, thruster-core-async-await/Cargo.toml, thruster-core-async-await/src/lib.rs, thruster-core/Cargo.toml, thruster-middleware/Cargo.toml, thruster-server/Cargo.toml, thruster/examples/most_basic_async.rs
**Note:** Also had to switch to tokio master thanks to [this](https://github.com/tokio-rs/tokio/issues/1087#issuecomment-491901368).
Delivers [#111]
=> chore: Update tokio to use most recent `.await` syntax [#111]

README.md, thruster-app/Cargo.toml, thruster-app/src/app.rs, thruster-async-await/Cargo.toml, thruster-async-await/src/lib.rs, thruster-context/Cargo.toml, thruster-core-async-await/Cargo.toml, thruster-core-async-await/src/errors.rs, thruster-core-async-await/src/lib.rs, thruster-core-async-await/src/middleware.rs, thruster-core/Cargo.toml, thruster-core/src/errors.rs, thruster-core/src/lib.rs, thruster-core/src/macros.rs, thruster-middleware/Cargo.toml, thruster-proc/Cargo.toml, thruster-proc/src/lib.rs, thruster-server/Cargo.toml, thruster/Cargo.toml, thruster/examples/most_basic_async.rs, thruster/src/lib.rs
Adds better error handling via a new macro -- `map_try`.
Error handling in Thruster at the moment is painful to say the least. It usually involves multiple levels of error handling and far too much indentation, or it involves layers of enums and implementations of contexts.
Ideally, we'd be able to simply have the solution:
```rust
async fn endpoint(context: BasicContext, next: MiddlewareNext<BasicContext>) -> Result<Ctx, ThrusterError> {
let s = some_call()?;
context.body(s);
Ok(context)
}
```
However, in order for the error to be properly mapped down the line, the resulting calls to `next` need access to a context, as the `context` they were supplied with as an argument is moved when `next(context)` is called. This means we need a thruster specific error, `ThrusterError`, that contains …
=> feat: Add better error handling [#108]

thruster/Cargo.toml, thruster/examples/errors_async.rs
To help with complex error handling on `ThrusterError` I added some convenience methods for downcasting the cause.
An additional proposal is to implement `StdError` for `ThrusterError` with `fn cause` returning the cause.
Thoughts?
=> Example error handling

thruster-app/Cargo.toml, thruster-async-await/Cargo.toml, thruster-context/Cargo.toml, thruster-core-async-await/Cargo.toml, thruster-core/Cargo.toml, thruster-core/src/request.rs, thruster-middleware/Cargo.toml, thruster-proc/Cargo.toml, thruster-server/Cargo.toml, thruster-server/src/server.rs, thruster/Cargo.toml
**Problem:** Currently, if a stream sends the headers and then doesn't immediately send the rest of the data, the connection drops the client (because Thruster panics since it doesn't have the right amount of data.)
**Solution:** If the buffer size doesn't equal the content-length, then we return `Ok(None)` so that we wait for more data in the stream.
=> bug: Fix multiple packets for a single request

.travis.yml, thruster-app/Cargo.toml, thruster-app/src/app.rs, thruster-core-async-await/src/middleware.rs, thruster-core/src/middleware.rs, thruster-core/src/route_parser.rs, thruster-core/src/route_tree/node.rs, thruster/Cargo.toml, thruster/examples/hello_world/context.rs, thruster/examples/hyper_most_basic.rs, thruster/examples/most_basic_async.rs, thruster/src/integration_tests.rs
**Issue:** If you have a route such as `/test/:id`, then curling `/test` will cause an end of cycle error.
**Solution:** This was happening, and wasn't caught by our tests, because of the optimization hash that we use to short circuit the route tree. Now we'll make sure that the route is a terminal non-wildcard route before adding it to the optimized tree. Also updated the enumerate method for nodes to return more useful information.
Should resolve #116
=> bug: Fix optimized route issue

publish_helper.sh, thruster-core/src/route_tree/node.rs
Can't use the default formatter and display because we need to recursively send down indentation information. This seemed like an easy hack around it.
=> Change name of `node.to_string` to not make clippy mad

thruster-app/src/testing.rs
Related to https://github.com/trezm/Thruster/issues/126
The generic `request` method available in the thruster_testing module is the only way to perform a test request and pass custom headers to it. It allows the developer to pass the HTTP method as a string, but when resolving the route it used a hardcoded `"GET"` instead of the user-supplied method.
This PR fixes it.
=> Actually use method parameter in thruster_testing::request

thruster-app/src/app.rs
Came across this small mistake while trying out Thruster.
=> Fixed incorrect example of use_sub_app

ROUTE_RESOLUTION.md, thruster-core/src/route_tree/node.rs, thruster/src/integration_async_tests.rs
There is an issue when adding a subapp with a wildcard wherein sibling routes are not properly propagated to the new tree. This means that having these routes:
`/:id`
`/do-something`
makes only `/:id` propagate correctly. This PR fixes that by always propagating sibling routes regardless of the presence of a wildcard.
=> bug: Fix subapp wildcard conflict issue

thruster/Cargo.toml, thruster/examples/unix_socket.rs, thruster/src/lib.rs, thruster/src/server/mod.rs, thruster/src/server/unix_hyper_server.rs
Adds a new server, `UnixHyperServer` that allows users to use local Unix sockets. Resolves [#147](https://github.com/trezm/Thruster/issues/147)
=> feat: Add unix hyper server

thruster-proc/Cargo.toml, thruster/Cargo.toml, thruster/examples/hyper_most_basic.rs, thruster/src/context/basic_hyper_context.rs, thruster/src/core/middleware.rs, thruster/src/core/route_tree/node.rs, thruster/src/integration_async_tests.rs
**Issue:** Right now, if you have code that looks like this:
```
app.use_middleware("/data", async_middleware![some_middleware]);
app.get("/data/:test", async_middleware![endpoint]);
```
for the request `GET /data/asdf`, `some_middleware` will not be called.
**Solution:** This is because we're comparing the method agnostic routes with method-ful routes. That is, we're comparing `/data` to `__GET__/data/:test`. The solution was to artificially ignore those first level of routes when traversing the tree. The root of the agnostic tree will be compared with the second level of the tree with methods.
=> bug: Method agnostic middleware fails in non root cases

thruster-proc/Cargo.toml, thruster/Cargo.toml, thruster/src/context/typed_hyper_context.rs
This is helpful for creating new contexts without needing to replicate the request (if it's not needed.)
=> feat: Allow typed contexts to be created without request

thruster-proc/Cargo.toml, thruster/Cargo.toml, thruster/src/server/ssl_hyper_server.rs, thruster/src/server/ssl_server.rs
[rustls](https://github.com/ctz/rustls) has proven to be able to handle edge cases better than native-tls in many circumstances. It's also nice to have a safe rust-based solution.
=> feat: Upgrade hyper_ssl_server to use rustls

thruster/Cargo.toml, thruster/src/middleware/file.rs
dashmap is a more performant and maintained alternative to chashmap.
chashmap is no longer maintained.
=> switch chashmap for dashmap

thruster-proc/src/lib.rs, thruster/Cargo.toml, thruster/examples/fast_hyper.rs, thruster/examples/hyper_most_basic.rs, thruster/src/context/basic_context.rs, thruster/src/context/basic_hyper_context.rs, thruster/src/context/fast_hyper_context.rs, thruster/src/context/hyper_request.rs, thruster/src/context/mod.rs, thruster/src/context/typed_hyper_context.rs, thruster/src/core/request.rs, thruster/src/core/route_parser.rs, thruster/src/core/route_tree/mod.rs, thruster/src/core/route_tree/node.rs, thruster/src/lib.rs, thruster/src/server/hyper_server.rs
- Adds in a "fast" example.
- Replaces shortcut hashmap with a vec. The reasoning behind this is that for most reasonably sized apps with ~30 routes, iterating through a vec is _still_ faster than a hashmap lookup. After that point, it's slower.
=> feat: Improve hyper related performance

thruster-proc/Cargo.toml, thruster/Cargo.toml, thruster/src/parser/tree.rs, thruster/src/server/hyper_server.rs
For static routes, add a quick map to get middleware quickly and efficiently.
=> chore: Add short circuiting to tree

thruster/src/context/basic_context.rs
As found on reddit, it looks like we were too aggressive cleaning up the response on `BasicContext`. We dropped the headers being set on the response! This should fix that.
=> bug: Fix basic context header setting

thruster/src/app/thruster_app.rs, thruster/src/parser/tree.rs
Allows developers to set an app to 'strict mode', which treats routes ending in a slash as distinct from the same route not ending with a slash.
=> feat: Add 'strict mode' parsing to app

thruster-proc/src/lib.rs
Proc macro attribute alias for `#[middleware_fn]`.
```rs
#[middleware]
async fn alias(mut context: Ctx, _next: MiddlewareNext<Ctx>) -> MiddlewareResult<Ctx> {
let val = "Hello, World!";
context.body(val);
Ok(context)
}
#[middleware_fn]
async fn original(mut context: Ctx, _next: MiddlewareNext<Ctx>) -> MiddlewareResult<Ctx> {
let val = "Hello, World!";
context.body(val);
Ok(context)
}
```
=> Middleware alias for middleware_fn

thruster/benches/app.rs, thruster/examples/actix_most_basic.rs, thruster/examples/error_handling.rs, thruster/examples/fast_homegrown.rs, thruster/examples/fast_hyper.rs, thruster/examples/hello_world.rs, thruster/examples/hyper_most_basic.rs, thruster/examples/multiple_services.rs, thruster/examples/mutable_state.rs, thruster/examples/nesting.rs, thruster/examples/profiling.rs, thruster/examples/unix_socket.rs, thruster/examples/using_state.rs, thruster/src/app/thruster_app.rs, thruster/src/context/basic_context.rs, thruster/src/core/middleware.rs, thruster/src/core/request.rs
Use the consuming builder pattern to make the construction of apps more intuitive.
New
```rs
let app = App::<Request, Ctx, ()>::new_basic().get("/plaintext", m![plaintext]);
let server = Server::new(app);
server.start("0.0.0.0", 4321);
```
Old
```rs
let mut app = App::<Request, Ctx, ()>::new_basic();
app.get("/plaintext", m![plaintext]);
let server = Server::new(app);
server.start("0.0.0.0", 4321);
```
=> Consuming app builder pattern

thruster-proc/Cargo.toml, thruster/Cargo.toml, thruster/examples/middleware.rs, thruster/examples/mutable_state.rs, thruster/src/app/thruster_app.rs, thruster/src/context/actix_request.rs, thruster/src/context/basic_actix_context.rs, thruster/src/context/basic_hyper_context.rs, thruster/src/context/hyper_request.rs, thruster/src/context/typed_hyper_context.rs, thruster/src/core/request.rs
In order to utilize match_and_resolve, which is helpful for limiting lifetimes, we need to have a better way to get and set params on the request. This adds a required trait to use the method, which will potentially break some implementations.
=> feat: Add request with params trait

README.md
crates.io doesn't use Rust syntax highlighting for `rs` codeblocks but does for `rust`
=> Fix `rs` codeblock for crates.io

thruster-proc/Cargo.toml, thruster/Cargo.toml, thruster/src/context/hyper_request.rs, thruster/src/parser/tree.rs
Query parameters were not being trimmed during route matching, so any request that had query parameters on it was not being matched unless it ended with a wildcard.
=> bug: Fix query parameter handling

thruster/examples/custom_middleware_with_auth.rs
Now it will use the proper tokio macro for async main functions.
=> chore: Update custom middleware example

thruster/src/app/testing_hyper_async.rs
The hyper testing was using an old version of 'resolve' instead of 'match_and_resolve' and therefore was not populating route params on the wrapped request object. '
=> bug: Fix params in hyper test harness

thruster/src/app/mod.rs
We were accidentally including hyper's body at all times rather than only when hyper servers were enabled.
=> bug: Only include hyper body sometimes

thruster/src/app/mod.rs
I didnt' realize that we were using the Body for non-hyper stuff as well. This changes it to be a u8 which should be valid for testing everything except for streams.
=> bug: Fix Testable trait so it's not hyper specific

thruster-proc/Cargo.toml, thruster/Cargo.toml, thruster/src/app/thruster_app.rs, thruster/src/parser/tree.rs
Wildcards when using router were not getting propagated down through the added router tree when there were no nodes. This, in general, is an edge case, however when attempting to apply a method like OPTIONS for CORS handling, often a subtree will not have any explicit OPTIONS routes. Previously, when the call was made, the route tree would see a terminal node in the default root of the OPTIONS tree for the router, and would use the 404 middleware that nodes default to. Now, if a node is default (and therefore non-terminal) the tree structure looks to see if the node is terminal and, if not, attempts to apply any wildcards before passing back the default middleware.
=> bug: Fix subtree wildcard propagation
